apiVersion: apps/v1
kind: Deployment
metadata:
 name: aks-deployment
spec:
 replicas: 5
 selector:
  matchLabels:
    app: lblaks
 template:
  metadata:
    labels:
      app: lblaks
  spec:
    containers:
    - name: myapp-container
      image: imranbergi/myfirstaksapp
      ports:
      - containerPort: 80
      imagePullPolicy: Always